export enum ActionTypes {
  GET_WEATHER_DATA = "GET_WEATHER_DATA",
  GET_WEATHER_DATA_SUCCESS = "GET_WEATHER_DATA_SUCCESS",
  GET_WEATHER_DATA_FAILURE = "GET_WEATHER_DATA_FAILURE",
  SEARCHED_WEATHER_DATA_SUCCESS = "SEARCHED_WEATHER_DATA_SUCCESS",
  SEARCHED_WEATHER_DATA_FAILURE = "SEARCHED_WEATHER_DATA_FAILURE",
  WEATHER_DEGREE_IS_CELSIUS = "WEATHER_DEGREE_IS_CELSIUS",
  WEATHER_DEGREE_IS_FAHRENHEIT = "WEATHER_DEGREE_IS_FAHRENHEIT",
  GET_LOCATION_FROM_MAP = "GET_LOCATION_FROM_MAP",
}
